Join space with invitation code
canopas/yourspace-flutter pull request #13
Opened 2024-05-29 12:42 UTC by cp-ishita-g

2024-05-30 12:36 UTC, cp-radhika-s requested changes

2024-05-30 12:36 UTC, cp-radhika-s commented on app/assets/locales/app_en.arb
> +  "join_space_already_joined_error_text": "You are already member of that space",
You are already member of this space

2024-05-30 12:36 UTC, cp-radhika-s commented on app/lib/ui/flow/home/components/home_top_bar.dart
>    final String title;
We need to pass the selected `space Id` as well.
From space Id we can get details of current space so we don't need `title` param

2024-05-30 12:36 UTC, cp-radhika-s commented on app/lib/ui/flow/home/components/home_top_bar.dart
> +    this.isCodeGetting = false,
isCodeGetting -> fetchingInviteCode

2024-05-30 12:36 UTC, cp-radhika-s commented on app/lib/ui/flow/home/home_screen_viewmodel.dart
> +  void updateSelectedSpaceName(SpaceInfo space) {
updateSelectedSpaceName -> updateSelectedSpace

2024-05-30 12:36 UTC, cp-radhika-s commented on app/lib/ui/flow/space/join/join_space_view_model.dart
> +      final joinSpaces = authService.currentUser?.space_ids ?? [];
joinSpaces -> userSpaces

2024-05-30 12:36 UTC, cp-radhika-s commented on data/lib/service/space_service.dart
> +  Stream<SpaceInfo?> streamCurrentSpaceInfo() async* {
```
 Stream<List<ApiSpace>> userSpacesStream(String userId) {
    return _apiSpaceService
        .getSpaceMemberByUserId(userId)
        .asyncMap(((List<ApiSpaceMember> members) async {
      print("XXX members ${members.length}");
      var spaces = await Future.wait(members
          .map((member) async => _apiSpaceService.getSpace(member.space_id)));
      return spaces.whereType<ApiSpace>().toList();
    }));
  }
  
 Future<Stream<List<SpaceInfo>>> getAllSpaceInfo() async {
    final String userId = _authRepository.currentUser?.id ?? '';
    print("XXX userId ${userId}");
    return userSpacesStream(userId).asyncMap((List<ApiSpace> spaces) async {
      var spaceInfos = await Future.wait(spaces.map((space) async {
        List<ApiSpaceMember> members =
            await _apiSpaceService.spaceMemberStream(space.id).first;
        var userInfos = await Future.wait(members.map((member) async {
          var user = await _apiUserService.getUser(member.user_id);
          return user == null
              ? null
              : UserInfo(
                  user: user, isLocationEnabled: member.location_enabled);
        }).toList());

        userInfos.removeWhere((userInfo) => userInfo == null);

        return SpaceInfo(apiSpace: space, apiUser: userInfos);
      }).toList());

      print("XXX getAllSpaceInfo called ${spaceInfos.length}");
      return spaceInfos;
    });
  }
```

2024-05-31 04:05 UTC, cp-ishita-g commented on data/lib/service/space_service.dart
> +  Stream<SpaceInfo?> streamCurrentSpaceInfo() async* {
i don't think so we need to make stream func here also, by streaming get member details calls we are getting live updates

2024-05-31 05:17 UTC, cp-ishita-g commented on app/lib/ui/flow/home/components/home_top_bar.dart
>    final String title;
we have state of selected space from there we can get space id to get current space data

2024-06-04 09:56 UTC, cp-radhika-s requested changes

2024-06-04 09:56 UTC, cp-radhika-s commented on app/lib/ui/flow/space/join/join_space_view_model.dart
> +      logger.e(
Notify the user with an appropriate message on failure, do the changes wherever require

2024-06-04 10:41 UTC, cp-radhika-s requested changes

2024-06-04 10:41 UTC, cp-radhika-s commented on app/lib/ui/flow/home/components/home_top_bar.dart
> +    selectedIndex = _getSelectedSpace();
We need to show the selected space always on top, so I think we don't need `selectedIndex`

2024-06-05 04:13 UTC, cp-radhika-s commented
We need to show a success popup on Space joined. Check Android flow

2024-06-05 04:20 UTC, cp-radhika-s requested changes

2024-06-05 04:20 UTC, cp-radhika-s commented on app/lib/ui/flow/home/components/home_top_bar.dart
> +  void didUpdateWidget(HomeTopBar oldWidget) {
Do we need this?

2024-06-05 04:20 UTC, cp-radhika-s commented on app/lib/ui/flow/space/join/join_space_screen.dart
> +          _joinSpaceError(context, state),
The error shouldn't move UI, Show an error as a popup like a banner. Check android implementation

2024-06-05 11:46 UTC, cp-radhika-s approved these changes

2024-06-05 11:53 UTC, merged