Setting screen
canopas/yourspace-flutter pull request #18
Opened 2024-06-04 05:36 UTC by cp-ishita-g

2024-06-06 08:42 UTC, cp-radhika-s requested changes

2024-06-06 08:42 UTC, cp-radhika-s commented on app/lib/ui/flow/setting/setting_screen.dart
> +      notifier.getUserSpace();
Let's make this call from notifier constuctor

2024-06-06 08:42 UTC, cp-radhika-s commented on app/lib/ui/flow/setting/setting_view_model.dart
> +      logger.e(
Show appropriate message to user on error, do changes wherever require

2024-06-06 08:42 UTC, cp-radhika-s commented on data/lib/api/auth/api_user_service.dart
> +        throw Exception('User not found');
Let's not throw an exception here, it's the caller's responsibility to handle the null data or failure

2024-06-07 05:10 UTC, cp-radhika-s requested changes

2024-06-07 05:10 UTC, cp-radhika-s commented on app/lib/ui/flow/setting/contact_support/contact_support_screen.dart
> +          showErrorSnackBar(context, state.error.toString());
which error we might have here?

2024-06-07 05:13 UTC, cp-ishita-g commented on app/lib/ui/flow/setting/contact_support/contact_support_screen.dart
> +          showErrorSnackBar(context, state.error.toString());
it was mistake, i am testing this

2024-06-07 05:15 UTC, cp-radhika-s requested changes

2024-06-07 05:15 UTC, cp-radhika-s commented on app/lib/ui/flow/setting/space/edit_space_view_model.dart
> +      state = state.copyWith(error: error);
set loading false on error, do changes wherever required

2024-06-07 05:17 UTC, cp-radhika-s requested changes

2024-06-07 05:17 UTC, cp-radhika-s commented on app/lib/ui/flow/setting/contact_support/contact_support_screen.dart
> +          notifier.submitSupportRequest();
We need to show a success message on request submitted

2024-06-07 05:56 UTC, cp-radhika-s approved these changes

2024-06-07 05:57 UTC, merged