Message Thread screen
canopas/yourspace-flutter pull request #19
Opened 2024-06-10 10:24 UTC by cp-ishita-g

- [ ] design message thread screen
- [ ] design empty view for message thread screen
       - for single member in space
       - for more than 1 member in space
- [ ] create model file and service file for message flow
- [ ] manage live data streaming for message thread screen

2024-06-10 12:25 UTC, kaushiksaliya commented
message thread if the user is signal and the last message is empty then make it vertical centre.

2024-06-10 12:27 UTC, kaushiksaliya commented
fix vertical padding in message thread screen.

2024-06-11 04:54 UTC, cp-radhika-s commented
> message thread if the user is signal and the last message is empty then make it vertical centre.

Threads always have at least one message,

2024-06-11 04:56 UTC, kaushiksaliya commented
in message thread when image try to load then show user icon instead of  loader.

2024-06-11 05:03 UTC, cp-radhika-s requested changes

2024-06-11 05:03 UTC, cp-radhika-s commented on app/lib/ui/flow/message/message_screen.dart
> +class MessageScreen extends ConsumerStatefulWidget {
Rename it to `ThreadListScreen`

2024-06-11 05:03 UTC, cp-radhika-s commented
Let's keep MR short, one per screen.
It'll be easy to review

2024-06-11 05:05 UTC, kaushiksaliya commented
if background color is primary then text color should be white.

2024-06-11 05:11 UTC, cp-ishita-g commented on app/lib/ui/flow/message/chat/chat_screen.dart
> +  final List<ApiUserInfo> users;
instead of fetching same again on next screen we can pass value from previous screen, it will make flow and load fast

2024-06-11 05:23 UTC, cp-ishita-g commented
> message thread if the user is signal and the last message is empty then make it vertical centre.



> > message thread if the user is signal and the last message is empty then make it vertical centre.
> 
> Threads always have at least one message,

i will fix this in next mr in chat screen so i can able to test easily

2024-06-11 05:31 UTC, kaushiksaliya commented
> > message thread if the user is signal and the last message is empty then make it vertical centre.
> 
> > > message thread if the user is signal and the last message is empty then make it vertical centre.
> > 
> > 
> > Threads always have at least one message,
> 
> i will fix this in next mr in chat screen so i can able to test easily

it is not fix name and last message time is not vertical centre.

2024-07-02 06:07 UTC, kaushiksaliya approved these changes

2024-07-02 06:10 UTC, merged