Implement places list screen.
canopas/yourspace-flutter pull request #26
Opened 2024-06-20 11:28 UTC by kaushiksaliya

Implement places list screen.

![Screenshot from 2024-06-17 16-15-56](https://github.com/canopas/yourspace-flutter/assets/140153665/60768876-e247-4e79-b9aa-211cd520c0bd)![Screenshot from 2024-06-20 16-54-31](https://github.com/canopas/yourspace-flutter/assets/140153665/fd9c4cd4-4205-4feb-b212-6c9f83f182aa)

![Screenshot from 2024-06-20 16-56-17](https://github.com/canopas/yourspace-flutter/assets/140153665/8924c0f9-001a-4ca0-8d37-db76c95aa0b3)![Screenshot from 2024-06-20 16-56-28](https://github.com/canopas/yourspace-flutter/assets/140153665/77c90d75-3e08-4d04-844f-c6ab8b093806)

2024-06-21 09:54 UTC, cp-radhika-s requested changes

2024-06-21 09:54 UTC, cp-radhika-s commented on app/assets/locales/app_en.arb
> +  "places_list_suggestion_add_your_place":"Add your {place}",
Let's remove `your`

2024-06-21 09:54 UTC, cp-radhika-s commented on app/lib/ui/flow/geofence/places/places_list_view.dart
> +          suggestions = newSuggestedPlace;
We should move suggestion state to view notifier, notifier will decide suggestion not the UI

2024-06-21 09:54 UTC, cp-radhika-s commented on app/lib/ui/flow/geofence/places/places_list_view_model.dart
> +      showDeletePlaceDialog: DateTime.now(),
Shouldn't it be bool?

2024-06-21 09:54 UTC, cp-radhika-s commented on data/lib/service/place_service.dart
> +  Future<void> deletePlace(String spaceId, String placeId) async {
Also need to remove it's sub collections

2024-06-21 10:08 UTC, kaushiksaliya commented on app/lib/ui/flow/geofence/places/places_list_view_model.dart
> +      showDeletePlaceDialog: DateTime.now(),
if we make it bool then we need to call function to false state after dialog close but here not.

2024-06-25 08:58 UTC, cp-radhika-s approved these changes

2024-06-25 08:58 UTC, merged