Implement add place screen
canopas/yourspace-flutter pull request #28
Opened 2024-06-24 14:04 UTC by kaushiksaliya

1. Implement Add new place screen.
2. Implement locate on map screen.
       - current user location not showing because of task is depending on location permission task.
3. implement choose new place screen.

2024-07-03 11:23 UTC, cp-ishita-g requested changes

2024-07-03 11:23 UTC, cp-ishita-g commented on app/lib/ui/app_route.dart
> +      builder: (_) => AddNewPlaceView(spaceId: spaceId),
as in whole project for screen we are using suffix screen so replace it with `AddNewPlaceScreen`

2024-07-03 11:23 UTC, cp-ishita-g commented on app/lib/ui/app_route.dart
> +      builder: (_) => ChoosePlaceNameView(
same goes here same suffix to screen and make this change everywhere

2024-07-03 11:23 UTC, cp-ishita-g commented on app/lib/ui/flow/geofence/add/addnew/add_new_place_view.dart
> +        TextField(
we can use here our defined `AppTextField` instead of using native

2024-07-03 11:23 UTC, cp-ishita-g commented on app/lib/ui/flow/geofence/add/placename/choose_place_name_view.dart
> +  final _textController = TextEditingController();
move this text controller to state

2024-07-03 11:23 UTC, cp-ishita-g commented on app/lib/ui/flow/geofence/add/placename/choose_place_name_view.dart
> +        CameraPosition(target: LatLng(lat, lng), zoom: defaultCameraZoom);
change `lng` -> `long`

2024-07-03 11:23 UTC, cp-ishita-g commented on data/lib/converter/time_converter.dart
> +}
this code is already present check it is used in `ApiThreadMessageModel`

2024-07-03 11:23 UTC, cp-ishita-g commented on data/lib/service/place_service.dart
> +    String? lng,
here also change typo `lng` -> `long`

2024-07-03 11:33 UTC, kaushiksaliya commented on app/lib/ui/flow/geofence/add/placename/choose_place_name_view.dart
> +        CameraPosition(target: LatLng(lat, lng), zoom: defaultCameraZoom);
no need this it is fine with lng it is easy to understand.

2024-07-03 11:35 UTC, kaushiksaliya commented on data/lib/converter/time_converter.dart
> +}
this ApiThreadMessageModel is not present in this branch code.

2024-07-03 11:36 UTC, cp-ishita-g commented on data/lib/converter/time_converter.dart
> +}
than you need to sync with main first

2024-07-03 11:37 UTC, cp-ishita-g commented on app/lib/ui/flow/geofence/add/placename/choose_place_name_view.dart
> +        CameraPosition(target: LatLng(lat, lng), zoom: defaultCameraZoom);
The short form for latitude is "lat." and for longitude is "long.", we can't use any of the abbreviation

2024-07-03 11:42 UTC, cp-ishita-g commented
![Screenshot 2024-07-03 at 5 12 08 PM](https://github.com/canopas/yourspace-flutter/assets/154948719/af870970-b1f6-41ee-aebf-069b506c2e7a)
change it according to figma design

2024-07-03 11:43 UTC, kaushiksaliya commented on data/lib/converter/time_converter.dart
> +}
this is sub branch no need to sync with main right now. when this mr merge with implement_map_view then i revert it.

2024-07-03 16:53 UTC, kaushiksaliya commented
> ![Screenshot 2024-07-03 at 5 12 08 PM](https://private-user-images.githubusercontent.com/154948719/345406925-af870970-b1f6-41ee-aebf-069b506c2e7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDcyOTgsIm5iZiI6MTcyMDAwNjk5OCwicGF0aCI6Ii8xNTQ5NDg3MTkvMzQ1NDA2OTI1LWFmODcwOTcwLWIxZjYtNDFlZS1hZWJmLTA2OWI1MDZjMmU3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QxMTQzMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOGYxZjA5YmM3MjYyNDYyNTI5NjU0NTM4MzllNWNlYTgxZTJkNGQ2YjgyZTgyNzRhYTNlNTQzZDQ4OTVkNmM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U2qtlIA9ooqTSlIV0KFYUh3i-h7BrwfTQ0nb8bGWvS0) change it according to figma design bottom line color and text color also

it is already according to figma check in device.

2024-07-04 12:05 UTC, cp-ishita-g approved these changes

2024-07-18 04:07 UTC, merged