Implement connection screen in onboard flow
canopas/yourspace-flutter pull request #36
Opened 2024-07-04 11:59 UTC by cp-ishita-g

- [x] implement connection screen
- [x] create secondary button class
- [x] manage join space and invite screen design according to onboard flow and normal flow

![join_space](https://github.com/canopas/yourspace-flutter/assets/154948719/150d2daf-89d5-4179-9bac-7127d11a3dfb) ![create_space](https://github.com/canopas/yourspace-flutter/assets/154948719/b5e50cea-2581-490c-ad8d-1fe358a2964e)

2024-07-16 03:16 UTC, kaushiksaliya commented
add bottom padding for next button in pickNameScreen.

2024-07-16 03:17 UTC, kaushiksaliya commented
on create space when we select any space name from suggestion and click on next button then getting permission_denied error.

2024-07-16 03:22 UTC, kaushiksaliya commented
on pick name screen when user click on system back button without adding name then do not show main screen. fix this flow.

2024-07-16 03:35 UTC, kaushiksaliya commented
no need to show this join space title if user coming from onboard.

![Screenshot from 2024-07-16 09-04-26](https://github.com/user-attachments/assets/f8daf56d-e921-40f6-b296-fe6390592490)

2024-07-22 04:38 UTC, cp-ishita-g commented on app/lib/ui/flow/space/join/join_space_screen.dart
>            _inviteCode(context),
it is upper case only can you please check again

2024-07-22 05:06 UTC, kaushiksaliya commented on app/lib/ui/flow/space/join/join_space_screen.dart
>            _inviteCode(context),
check this.

![Screenshot from 2024-07-22 10-35-58](https://github.com/user-attachments/assets/ce3d81e2-16b8-4549-a22b-2b8618c89c92)

2024-07-22 08:38 UTC, cp-radhika-s requested changes

2024-07-22 08:38 UTC, cp-radhika-s commented on app/ios/Runner/Info.plist
> +    <string>ABCDFGHI</string>
Replace `<string>ABCDFGHI</string>` with `<string>YOUR MAP API KEY</string>`

2024-07-22 08:50 UTC, cp-ishita-g commented on app/ios/Runner/Info.plist
> +    <string>ABCDFGHI</string>
it's it will be published

2024-07-22 09:10 UTC, cp-radhika-s commented on app/ios/Runner/Info.plist
> +    <string>ABCDFGHI</string>
I'm not saying to add api key, just add this text `YOUR MAP API KEY`

2024-07-22 09:36 UTC, kaushiksaliya approved these changes

2024-07-22 11:53 UTC, cp-radhika-s requested changes

2024-07-22 11:53 UTC, cp-radhika-s commented on app/lib/ui/flow/auth/sign_in/sign_in_method_screen.dart
> +      navigateToHome();
Don't we need to check for `mounted`?

2024-07-22 11:53 UTC, cp-radhika-s commented on app/lib/ui/flow/onboard/pick_name_screen.dart
> +                _notifier.saveUser(widget.user ?? _notifier.user!);
Let's not access notifier property directly, it should be through state only

2024-07-22 12:02 UTC, cp-radhika-s approved these changes

2024-07-22 12:03 UTC, merged