Handle notification tap for place added
canopas/yourspace-flutter pull request #65
Opened 2024-07-31 04:44 UTC by cp-ishita-g

2024-08-06 10:27 UTC, cp-ishita-g commented
@kaushiksaliya please review

2024-08-06 10:31 UTC, cp-radhika-s requested changes

2024-08-06 10:31 UTC, cp-radhika-s commented on app/android/app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.WAKE_LOCK"/>
Why do we need this permission?

2024-08-06 10:31 UTC, cp-radhika-s commented on app/android/app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.VIBRATE"/>
Why this permission?

2024-08-06 10:31 UTC, cp-radhika-s commented on app/android/app/src/main/AndroidManifest.xml
> +            android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
What is use of this?

2024-08-06 10:31 UTC, cp-radhika-s commented on app/android/app/src/main/AndroidManifest.xml
> +        <meta-data android:name="firebase_messaging_auto_init_enabled" android:value="false" />
why do we need`firebase_analytics_collection_deactivated` & `firebase_messaging_auto_init_enabled`?

2024-08-06 10:31 UTC, cp-radhika-s commented on app/android/app/src/main/res/drawable/splash_inset.xml
> +<?xml version="1.0" encoding="utf-8"?>
Why do we need this?

2024-08-06 10:31 UTC, cp-radhika-s commented on app/android/app/src/main/res/values-night/styles.xml
> +        <item name="android:windowSplashScreenAnimatedIcon">@drawable/splash_inset</item>
Why do we have splash screen changes here?

2024-08-06 10:31 UTC, cp-radhika-s commented on app/android/app/src/main/res/values/styles.xml
> +        <item name="android:windowSplashScreenAnimatedIcon">@drawable/splash_inset</item>
Remove this keep default behaviour

2024-08-06 10:31 UTC, cp-radhika-s commented on app/lib/domain/fcm/notification_handler.dart
> +      AppRoute.placesList(spaceId).push(context);
Don't we need to also set this space id as the current selected space id?

2024-08-06 10:31 UTC, cp-radhika-s commented on app/lib/domain/fcm/notification_handler.dart
> +  'Notifications',
YourSpace Notification

2024-08-06 10:31 UTC, cp-radhika-s commented on app/lib/main.dart
> +  await Permission.notification.isDenied.then((value) {
We shouldn't  ask for permission here, we have enable permission screen, where we're asking for required permission, check android for reference

2024-08-06 10:31 UTC, cp-radhika-s commented on app/lib/ui/flow/home/home_screen.dart
> +      notifier.getAllSpaces();
`notifier.getAllSpaces();` let's make this call from notifier itself

2024-08-06 10:37 UTC, cp-ishita-g commented on app/lib/main.dart
> +  await Permission.notification.isDenied.then((value) {
this implementation was not done by me and don't know reason why @kaushiksaliya ask for permission here

2024-08-06 10:38 UTC, cp-ishita-g commented on app/android/app/src/main/res/values/styles.xml
> +        <item name="android:windowSplashScreenAnimatedIcon">@drawable/splash_inset</item>
this changes was done by @kaushiksaliya i merge main changes in mine and reset that commit so it is showing my changes and same for above two comment

2024-08-06 10:42 UTC, cp-ishita-g commented on app/android/app/src/main/AndroidManifest.xml
> +        <meta-data android:name="firebase_messaging_auto_init_enabled" android:value="false" />
before i am not getting notification so i added this permission and also above added comment

2024-08-06 10:43 UTC, cp-ishita-g commented on app/lib/domain/fcm/notification_handler.dart
> +      AppRoute.placesList(spaceId).push(context);
why to make it current selected space here, user is just getting notified about that place which was added this by user, i don't think there is need to make it current space id

2024-08-06 10:51 UTC, kaushiksaliya commented on app/lib/main.dart
> +  await Permission.notification.isDenied.then((value) {
I am not adding this notification permission request. if you asking for location permission then it is required for geolocator .

2024-08-06 10:55 UTC, kaushiksaliya commented on app/android/app/src/main/res/values/styles.xml
> +        <item name="android:windowSplashScreenAnimatedIcon">@drawable/splash_inset</item>
we have to app logo one is for app icon and other is for splash with white background and also splash screen icon color is different.

2024-08-06 11:25 UTC, cp-radhika-s commented on app/android/app/src/main/AndroidManifest.xml
> +        <meta-data android:name="firebase_messaging_auto_init_enabled" android:value="false" />
I don't think it has anything to do with notification

2024-08-06 11:26 UTC, cp-radhika-s commented on app/lib/domain/fcm/notification_handler.dart
> +      AppRoute.placesList(spaceId).push(context);
here we're navigating the user to the places screen, which is deepened on selected space

2024-08-06 11:26 UTC, cp-ishita-g commented on app/android/app/src/main/AndroidManifest.xml
> +        <meta-data android:name="firebase_messaging_auto_init_enabled" android:value="false" />
i removed all unwanted permission, and i added this from any of the reference,

2024-08-06 11:29 UTC, cp-ishita-g commented on app/lib/domain/fcm/notification_handler.dart
> +      AppRoute.placesList(spaceId).push(context);
it is when we are in app, it is based on selected space id but here we are getting space id from remote notification message, so don't need to update current space id

2024-08-06 11:30 UTC, cp-radhika-s requested changes

2024-08-06 11:30 UTC, cp-radhika-s commented on data/lib/api/auth/api_user_service.dart
> +      await registerFcmToken(currentUser?.id ?? '',  deviceToken);
let's not pass an empty string, use the not null operator

2024-08-06 11:30 UTC, cp-radhika-s commented on data/lib/api/auth/api_user_service.dart
> +      await registerFcmToken(currentUser?.id ?? '',  deviceToken);
Are we updating the session `isActive` flag when the user logout? if not then let's fix it

2024-08-06 11:32 UTC, cp-radhika-s requested changes

2024-08-06 11:32 UTC, cp-radhika-s commented on app/android/app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.WAKE_LOCK"/>
Let me know why we need this

2024-08-06 11:34 UTC, cp-ishita-g commented on app/android/app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.WAKE_LOCK"/>
are you talking about wave lock than that is added by @kaushiksaliya and receive boot completed permission error i added when i am not getting notification on android side

2024-08-06 13:16 UTC, kaushiksaliya commented on app/android/app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.WAKE_LOCK"/>
No, I have not added this permission.

2024-08-07 04:06 UTC, cp-radhika-s commented
Where do we ask for notification permission?

2024-08-07 04:06 UTC, cp-radhika-s commented
Please fix pipelines

2024-08-07 04:10 UTC, cp-ishita-g commented
> Where do we ask for notification permission?

it was asked from enable permission view file, do we need to call again

2024-08-07 04:22 UTC, cp-radhika-s approved these changes

2024-08-07 04:22 UTC, merged